# Generated by Django 6.1.1 on 2026-09-04 08:38

from django.db import migrations, models


MOCK_PROJECTS = (
    {
        'slug': 'depi-taskflow',
        'title': 'TaskFlow',
        'project_type': 'Android / Task management',
        'summary': 'A sample task manager for organizing daily to-dos, setting priorities, and keeping track of progress.',
        'features': [
            'Create, update, and complete tasks',
            'Save tasks locally for offline access',
        ],
        'tech_stack': 'Kotlin, Jetpack Compose, Room',
        'display_order': 1,
    },
    {
        'slug': 'depi-weatherly',
        'title': 'Weatherly',
        'project_type': 'Android / Weather forecast',
        'summary': 'A sample weather app for exploring city forecasts and turning API responses into a clear mobile experience.',
        'features': [
            'Search cities and explore daily forecasts',
            'Handle loading, empty, and error states',
        ],
        'tech_stack': 'Kotlin, Retrofit, Coroutines',
        'display_order': 2,
    },
    {
        'slug': 'depi-spendwise',
        'title': 'SpendWise',
        'project_type': 'Android / Expense tracking',
        'summary': 'A sample expense tracker for recording everyday spending, grouping purchases, and reviewing monthly totals.',
        'features': [
            'Organize expenses by category',
            'Review spending with monthly summaries',
        ],
        'tech_stack': 'Kotlin, Room, MVVM',
        'display_order': 3,
    },
)


def add_mock_projects(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    for project in MOCK_PROJECTS:
        defaults = {key: value for key, value in project.items() if key != 'slug'}
        defaults.update(section='depi', is_mock=True, featured=True)
        Project.objects.using(schema_editor.connection.alias).get_or_create(
            slug=project['slug'], defaults=defaults,
        )


def remove_mock_projects(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    Project.objects.using(schema_editor.connection.alias).filter(
        slug__in=[project['slug'] for project in MOCK_PROJECTS],
        section='depi', is_mock=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_lodgitech_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Label sample content as a mock project until real project details are added.'),
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('selected', 'Selected work'), ('depi', 'DEPI projects')], default='selected', max_length=20),
        ),
        migrations.RunPython(add_mock_projects, remove_mock_projects),
    ]
