# Generated by Django 6.1.1 on 2026-09-04 09:05

from django.db import migrations, models


def add_iti_mock_project(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    Project.objects.using(schema_editor.connection.alias).get_or_create(
        slug='iti-web-development-project',
        defaults={
            'title': 'Web Development Project',
            'project_type': 'Web application / Summer training',
            'summary': (
                'A placeholder for a Django / Flask project from my ITI Summer Training. '
                'Full project details will be added soon.'
            ),
            'features': [],
            'tech_stack': 'Python, Django, Flask',
            'section': 'iti',
            'is_mock': True,
            'featured': True,
            'display_order': 1,
        },
    )


def remove_iti_mock_project(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    Project.objects.using(schema_editor.connection.alias).filter(
        slug='iti-web-development-project', section='iti', is_mock=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_depi_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('selected', 'Selected work'), ('depi', 'DEPI projects'), ('iti', 'ITI Summer Training')], default='selected', max_length=20),
        ),
        migrations.RunPython(add_iti_mock_project, remove_iti_mock_project),
    ]
